language: go

notifications:
  email: false

install:
  - go get github.com/kardianos/govendor
  - go get github.com/stretchr/testify/assert
  - govendor sync

script:
  - GOOS=linux GOARCH=amd64 go test ./...
  - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Commit=${TRAVIS_COMMIT} -X main.Build=$(date +%Y%m%d) -s -w" -o go-audit-linux
# Debug purpose to check deps
  - file go-audit-linux && ldd go-audit-linux 

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - go-audit-linux
  on:
    tags: true
    repo: BaritoLog/go-audit
    all_branches: true

